{
    aleksSad : "bibLenin",
    arbat : "bibLenin",
    bibLenin : "bibLenin",
    belorusKolc : "belorus",
    belorusRad : "belorus",
    borov : "bibLenin",
    kitajKaluzh : "kitaj",
    kitajTagan : "kitaj",
    kuznec : "kuznecLub",
    lubyanka : "kuznecLub",
    mayakov : 1,
    novokuzn : "tretNov",
    oktyabrKolc : "oktyabr",
    oktyabrRad : "oktyabr",
    ohot: "plOhTeatr",
    plRev: "plOhTeatr",
    prospMiraKolc: "prospMira",
    prospMiraRad : "prospMira",
    pushk: "chehPushTver",
    sreten: "chistTurgSret",
    suxarev : 1,
    tver: "chehPushTver",
    teatr: "plOhTeatr",
    tretyakovKaluzh : "tretNov",
    tretyakovKalin : "tretNov",
    turgen : "chistTurgSret",
    cheh: "chehPushTver",
    chistPrud : "chistTurgSret"
}